Add support for SMASH

diff --git a/cardano_node_tests/cluster_scripts/alonzo/start-cluster-hfc b/cardano_node_tests/cluster_scripts/alonzo/start-cluster-hfc
--- a/cardano_node_tests/cluster_scripts/alonzo/start-cluster-hfc
+++ b/cardano_node_tests/cluster_scripts/alonzo/start-cluster-hfc
@@ -97,6 +97,7 @@ cp "$SCRIPT_DIR"/cardano-node-* "$STATE_CLUSTER"
 cp "$SCRIPT_DIR"/topology-*.json "$STATE_CLUSTER"
 cp "$SCRIPT_DIR/byron-params.json" "$STATE_CLUSTER"
 cp "$SCRIPT_DIR/dbsync-config.yaml" "$STATE_CLUSTER"
+cp "$SCRIPT_DIR/admins.txt" "$STATE_CLUSTER"
 cp "$SCRIPT_DIR/supervisor.conf" "$STATE_CLUSTER"
 cp "$SCRIPT_DIR/genesis.spec.json" "$STATE_CLUSTER/shelley/genesis.spec.json"
 
@@ -104,6 +105,12 @@ cp "$SCRIPT_DIR/genesis.spec.json" "$STATE_CLUSTER/shelley/genesis.spec.json"
 if [ -n "${DBSYNC_REPO:-""}" ]; then
   [ -e "$DBSYNC_REPO/db-sync-node/bin/cardano-db-sync" ] || \
     { echo "The \`$DBSYNC_REPO/db-sync-node/bin/cardano-db-sync\` not found, line $LINENO" >&2; exit 1; }  # assert
+
+  # enable smash service
+  if [ -n "${USE_SMASH:-""}" ]; then
+    [ -e "$DBSYNC_REPO/smash-server/bin/cardano-smash-server" ] || \
+      { echo "The \`$DBSYNC_REPO/smash-server/bin/cardano-smash-server\` not found, line $LINENO" >&2; exit 1; }  # assert
+  fi
 
   # create clean database
   "$SCRIPT_DIR/postgres-setup.sh"
@@ -114,6 +121,12 @@ if [ -n "${DBSYNC_REPO:-""}" ]; then
 command=$SCRIPT_DIR/run_dbsync.sh
 stderr_logfile=./$STATE_CLUSTER_NAME/dbsync.stderr
 stdout_logfile=./$STATE_CLUSTER_NAME/dbsync.stdout
+autostart=false
+
+[program:smash]
+command=$SCRIPT_DIR/run_smash.sh
+stderr_logfile=./$STATE_CLUSTER_NAME/smash.stderr
+stdout_logfile=./$STATE_CLUSTER_NAME/smash.stdout
 autostart=false
 EoF
 fi
@@ -403,6 +416,12 @@ wait_for_era "Shelley"
 if [ -n "${DBSYNC_REPO:-""}" ]; then
   echo "Starting db-sync"
   supervisorctl start dbsync
+fi
+
+# start smash
+if [ -n "${USE_SMASH:-""}" ]; then
+  echo "Starting smash"
+  supervisorctl start smash
 fi
 
 sleep "$PROPOSAL_DELAY"
